version: "3"
services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx
      - ./nginx/certs:/etc/ssl/private
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always

  nextjs:
    build: ./nextjs
    ports:
      - 3000:3000
    depends_on:
      - nginx

  strapi:
    container_name: strapi
    image: strapi/strapi
    environment:
      DATABASE_CLIENT: mongo
      DATABASE_HOST: mongo
      DATABASE_PORT: 27017
      DATABASE_NAME: ${MONGODB_DBNAME}
      DATABASE_USERNAME: ${MONGODB_ROOT_USERNAME}
      DATABASE_PASSWORD: ${MONGODB_ROOT_PASSWORD}
    volumes:
      - ./strapi:/srv/app
    ports:
      - 1337:1337
    depends_on:
      - mongo
      - nginx
  #    command: yarn add strapi-plugin-graphql

  mongo:
    container_name: mongo
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: ${MONGODB_DBNAME}
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    #restart: unless-stopped
